services:
  lesta:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    image: dongjineee/lesta:01
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - ../../LeSTA:/root/lesta_ws/src/LeSTA
      # - ../../../../dataset:/root/lesta_ws/src/dataset
      
    environment:
      - ROS_IP=127.0.0.1
    command: "/bin/bash"
    shm_size: 128M